# Generated by Django 5.0.6 on 2024-08-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='org',
            new_name='acc_id',
        ),
    ]
