# Generated by Django 5.0.6 on 2024-08-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_rename_org_drug_acc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
