# Generated by Django 5.0.6 on 2024-08-16 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cart', '0002_cartitem_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='acc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts', unique=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
