# Generated by Django 5.0.6 on 2024-08-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_acc_id_alter_cartitem_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='total_cost',
            new_name='item_cost',
        ),
        migrations.AddField(
            model_name='cart',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
