# Generated by Django 5.0.6 on 2024-08-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_rename_total_cost_cartitem_item_cost_cart_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='acc_id',
            new_name='buyer_id',
        ),
    ]
