# Generated by Django 5.0.6 on 2024-08-19 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cart', '0005_rename_acc_id_cart_buyer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='buyer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts'),
        ),
    ]
