# Generated by Django 5.0.6 on 2024-08-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='acc_id',
            new_name='seller_id',
        ),
    ]
