# Generated by Django 5.0.6 on 2024-08-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('seller', 'Company'), ('buyer', 'Pharmacy')], max_length=50),
        ),
    ]
