# Generated by Django 5.0.6 on 2024-08-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('user_role', '0002_alter_userrole_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('acc_id',), name='unique_role_per_account'),
        ),
    ]
